import React from "react";
// Icons used by the app are vendored locally (generated by scripts/build-icons.mjs)
// so they render synchronously with no network request. The CDN fetch below stays
// only as a fallback for any icon name that wasn't picked up at build time.
import { LUCIDE_ICONS } from "../../../src/generated/lucide-icons.js";

const cache = new Map();
const pending = new Map();

/** Inline Lucide icon. Renders the vendored SVG body synchronously; for any name
    not vendored, fetches from the lucide-static CDN once and caches it. Either way
    it renders inline so it inherits currentColor. */
export function Icon({ name, size = 16, strokeWidth = 2, style, className }) {
  const local = LUCIDE_ICONS[name];
  const [inner, setInner] = React.useState(() => local || cache.get(name) || null);

  React.useEffect(() => {
    let alive = true;
    if (local) { setInner(local); return; }
    if (cache.has(name)) { setInner(cache.get(name)); return; }
    if (!pending.has(name)) {
      pending.set(name, fetch("https://unpkg.com/lucide-static@0.469.0/icons/" + name + ".svg")
        .then((r) => (r.ok ? r.text() : Promise.reject(new Error("icon " + name))))
        .then((text) => {
          const body = text.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
          cache.set(name, body);
          return body;
        }));
    }
    pending.get(name).then((body) => { if (alive) setInner(body); }).catch(() => {});
    return () => { alive = false; };
  }, [name, local]);

  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      className={className}
      style={{ flexShrink: 0, display: "inline-block", verticalAlign: "middle", ...style }}
      dangerouslySetInnerHTML={inner ? { __html: inner } : undefined}
    />
  );
}
