// Pocket — vendor the Lucide icons the app actually uses into a local module,
// so the Icon component renders synchronously with no runtime network call.
// Scans the source for icon-name string literals, keeps only those that match a
// real lucide-static SVG, and writes src/generated/lucide-icons.js.
//
// Runs automatically before `npm run dev` / `npm run build` (and via `npm run icons`).
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const ICONS_DIR = join(ROOT, "node_modules", "lucide-static", "icons");
const OUT_FILE = join(ROOT, "src", "generated", "lucide-icons.js");

// Directories scanned for icon usages.
const SCAN_DIRS = [join(ROOT, "src"), join(ROOT, "Pocket Design System")];
const SCAN_EXT = /\.(jsx?|tsx?)$/;

// Patterns that introduce an icon name. `name="..."` is broad on purpose — false
// positives are filtered out below because they won't match a real SVG file.
const PATTERNS = [
  /\bicon\s*[:=]\s*["']([a-z0-9-]+)["']/g,
  /\bname\s*=\s*["']([a-z0-9-]+)["']/g,
  /\bnewIcon\s*[:=]\s*["']([a-z0-9-]+)["']/g,
];

// A few icons are referenced indirectly (e.g. computed) — pin them so they're
// always vendored regardless of how the scan goes.
const ALWAYS = ["loader", "loader-circle", "triangle-alert", "wrench", "x", "check", "copy", "download", "star", "chevron-right", "chevron-down", "sun", "moon", "search", "info", "upload"];

function walk(dir, out) {
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir)) {
    if (entry === "node_modules" || entry === "generated" || entry.startsWith(".")) continue;
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, out);
    else if (SCAN_EXT.test(entry)) out.push(full);
  }
  return out;
}

function extractInner(svg) {
  // Strip the leading license comment + opening <svg ...> and the closing </svg>,
  // leaving just the path children (same shape the runtime previously fetched).
  return svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();
}

const candidates = new Set(ALWAYS);
for (const file of walk(SCAN_DIRS[0], walk(SCAN_DIRS[1], []))) {
  const src = readFileSync(file, "utf8");
  for (const re of PATTERNS) {
    let m;
    re.lastIndex = 0;
    while ((m = re.exec(src))) candidates.add(m[1]);
  }
}

const icons = {};
const missing = [];
for (const name of [...candidates].sort()) {
  const svgPath = join(ICONS_DIR, name + ".svg");
  if (existsSync(svgPath)) icons[name] = extractInner(readFileSync(svgPath, "utf8"));
  else missing.push(name);
}

mkdirSync(dirname(OUT_FILE), { recursive: true });
const lines = Object.keys(icons).map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(icons[n])},`);
const out = `// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Inlined Lucide icon bodies (lucide-static@0.469.0) for the icons the app uses,
// so <Icon> renders with no runtime network request. Re-run \`npm run icons\`.
export const LUCIDE_ICONS = {
${lines.join("\n")}
};
`;
writeFileSync(OUT_FILE, out, "utf8");

const skipped = missing.filter((n) => !ALWAYS.includes(n) || existsSync(join(ICONS_DIR, n + ".svg")));
console.log(`[build-icons] vendored ${Object.keys(icons).length} icons → ${OUT_FILE.replace(ROOT + "\\", "").replace(ROOT + "/", "")}`);
if (skipped.length) console.log(`[build-icons] (${skipped.length} non-icon candidates ignored)`);
